version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - appnet

  backend:
    build:
      context: ./Back-nestjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook-test/31db848d-10b2-4d20-9470-bbe94a79bc67
    networks:
      - appnet

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    networks:
      - appnet
    environment:
      - N8N_HOST=192.168.0.228
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
    volumes:
      - /home/it/n8n/n8n_data:/home/node/.n8

networks:
  appnet:
    driver: bridge
